# Generated by Django 4.2.11 on 2025-05-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0)),
                ('assists', models.FloatField(default=0)),
                ('rebounds', models.FloatField(default=0)),
                ('steals', models.FloatField(default=0)),
                ('blocks', models.FloatField(default=0)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_stats', to='player_stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('OPS', models.FloatField(default=0)),
                ('K', models.FloatField(default=0)),
                ('AB', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_stats', to='player_stats.player')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
